#! /usr/bin/perl
# (c) LGPL 2008-2010 Steve Schnepp <steve.schnepp@pwkf.org>
# Parsing X11 rgb.txt to libnds RGB15 format

use strict;

my %seen_colors;

print "/* Autogenerated colors file, DO NOT EDIT */\n";
while (<>) {
	chop;
	next unless m/(\d+)\s+(\d+)\s+(\d+)\s+(\S+)/;
	my ($r, $g, $b, $color) = ($1, $2, $3, $4);

	# replacing spaces with _ in color name
	$color =~ s/ /_/g;

	# No duplicate allowed
	next if $seen_colors{$color}++;

	# dithering from the 0-255 span to 0-31 one
	$r = int($r / 8);
	$g = int($g / 8);
	$b = int($b / 8);
	print "#define RGB15_$color RGB15($r, $g, $b)";
	print "\n";
}
